# Generated by Django 4.2.5 on 2023-10-04 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_employee_newsphoto_projectsphoto_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='email',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='hire_date',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='phone_number',
        ),
    ]
