# Generated by Django 4.2.5 on 2023-10-04 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_employee_bio_remove_employee_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsphoto',
            name='image',
            field=models.ImageField(upload_to='static/news_photos/'),
        ),
        migrations.AlterField(
            model_name='projectsphoto',
            name='image',
            field=models.ImageField(upload_to='static/projects_photos/'),
        ),
    ]
