# Generated by Django 4.2.5 on 2023-10-17 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_projecttheme_project_theme"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="theme",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="main.projecttheme",
            ),
        ),
    ]
