# Generated by Django 4.2.5 on 2023-10-17 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_project_theme'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='photos',
        ),
        migrations.AddField(
            model_name='news',
            name='photo',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='main.newsphoto'),
        ),
    ]
