# Generated by Django 4.2.5 on 2023-11-07 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_employee_last_name_alter_employee_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='theme',
        ),
        migrations.AddField(
            model_name='project',
            name='theme',
            field=models.ManyToManyField(null=True, to='main.projecttheme'),
        ),
    ]
