# Generated by Django 4.2.5 on 2023-11-08 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_remove_project_theme_project_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='main_photo',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.projectsphoto'),
        ),
        migrations.AddField(
            model_name='projectsphoto',
            name='display_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='project',
            name='photos',
            field=models.ManyToManyField(related_name='project_photos', to='main.projectsphoto'),
        ),
        migrations.AlterField(
            model_name='project',
            name='theme',
            field=models.ManyToManyField(blank=True, null=True, to='main.projecttheme'),
        ),
    ]
