# Generated by Django 4.2.5 on 2023-11-08 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_project_main_photo_projectsphoto_display_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='theme',
            field=models.ManyToManyField(blank=True, to='main.projecttheme'),
        ),
    ]
