# Generated by Django 4.2.5 on 2023-11-08 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_project_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectsphoto',
            name='is_main',
            field=models.BooleanField(default=False, verbose_name='Show as main photo on homepage'),
        ),
    ]
