# Generated by Django 4.2.5 on 2023-11-10 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_project_client_project_full_space_project_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='location',
            field=models.CharField(default='Испания', max_length=100),
        ),
    ]
