# Generated by Django 4.2.5 on 2023-11-10 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_alter_project_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='team',
            field=models.CharField(default='команда', max_length=50),
        ),
        migrations.AlterField(
            model_name='project',
            name='client',
            field=models.CharField(default='клиент', max_length=50),
        ),
        migrations.AlterField(
            model_name='project',
            name='full_space',
            field=models.CharField(default='общая площадь', max_length=50),
        ),
        migrations.AlterField(
            model_name='project',
            name='space',
            field=models.CharField(default='площадь', max_length=50),
        ),
        migrations.AlterField(
            model_name='project',
            name='years',
            field=models.CharField(default='года', max_length=50),
        ),
    ]
