# Generated by Django 4.2.5 on 2023-11-15 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_project_team_alter_project_client_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectsphoto',
            name='is_main',
        ),
    ]
