# Generated by Django 4.2.5 on 2023-11-15 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_remove_project_main_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='main_image',
            field=models.ImageField(default='static/project_photos/рен1.jpg', upload_to='static/projects_photos/'),
        ),
    ]
