# Generated by Django 4.2.5 on 2023-11-15 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_projectphotoorder_alter_project_photos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='photos',
        ),
    ]
