# Generated by Django 4.2.5 on 2023-11-15 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_project_photos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='photos',
        ),
        migrations.AddField(
            model_name='project',
            name='photos',
            field=models.ManyToManyField(related_name='project_photos', to='main.projectsphoto'),
        ),
        migrations.DeleteModel(
            name='ProjectPhotoOrder',
        ),
    ]
