# Generated by Django 4.2.5 on 2023-11-15 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_alter_project_photos_delete_projectphotoorder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='photos',
        ),
    ]
