# Generated by Django 4.2.5 on 2023-11-15 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_remove_project_photos'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='photos',
            field=models.ManyToManyField(related_name='project_photos', to='main.projectsphoto'),
        ),
    ]
